# Generated by Django 2.1.4 on 2019-01-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdolInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=100)),
                ('anime_manga_fan_score', models.IntegerField(default=0)),
                ('eat_score', models.IntegerField(default=0)),
                ('artistic_score', models.IntegerField(default=0)),
                ('music_fan_score', models.IntegerField(default=0)),
                ('travel_score', models.IntegerField(default=0)),
                ('athletic_score', models.IntegerField(default=0)),
                ('animal_like_score', models.IntegerField(default=0)),
                ('caring_score', models.IntegerField(default=0)),
                ('read_score', models.IntegerField(default=0)),
                ('cook_score', models.IntegerField(default=0)),
            ],
        ),
    ]
