# Generated by Django 2.1.4 on 2019-01-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idolinformation',
            name='name',
            field=models.CharField(default='NULL', max_length=60),
        ),
    ]
