# Generated by Django 2.1.4 on 2019-01-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_idolinformation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='idolinformation',
            name='generation',
            field=models.CharField(default='1st', max_length=5),
        ),
    ]
